config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :tasks do
    resources :searches, only: :index
  end
  resources :tasks do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get "following"
      get "followers"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :receive_user, class_name: 'User'
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_user, only: [:index, :create, :show]
  # before_action :require_user_logged_in

  def index
    # send_ids = current_user.messages.where(receive_user_id: @user.id).pluck(:id)
    # receive_ids = @user.messages.where(receive_user_id: current_user.id).pluck(:id)
    # @messages = Message.where(id: send_ids + receive_ids).order(created_at: :desc)
    # @message = Message.new
  end

  def new

  end
  
  def create
    # @message = current_user.messages.build(message_params)
    # @message.receive_user_id = @user.id
    # if @message.save
    #   flash[:success] = "メッセージを送信しました。"
    #   redirect_back(fallback_location: root_path)
    # else
    #   flash[:denger] = "メッセージ送信に失敗しました。"
    #   redirect_back(fallback_location: root_path)
    # end
  end
  
  def destroy
    # @message = Message.find(params[:id])
    # @message.destroy
    # flash[:success] = "メッセージを削除しました。"
    # redirect_back(fallback_location: root_path)
  end
  
  def show
    # send_ids = current_user.messages.where(receive_user_id: @user.id).pluck(:id)
    # receive_ids = @user.messages.where(receive_user_id: current_user.id).pluck(:id)
    # @messages = Message.where(id: send_ids + receive_ids).order(created_at: :desc)
    # @message = Message.new
  end

  private
  # def set_user
  #   @user = Message.find(params[:id])
  # end

  # def message_params
  #   params.require(:message).permit(:content)
  # end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
-# %h2(style="padding-top: 100px;") メッセージ一覧
-# - user = User.find_by(id: @message.receive_user_id)
-# - @messages.each do |message|
-#   %div
-#     .media-left
-#       %img.media-object.img-circle{alt: "", src: gravatar_url(message.user, { size: 50 })}/
-#     .media-body
-#       %div
-#         = link_to message.user.nickname, user_path(message.user)
-#         %span.text-muted
-#           posted at #{message.created_at}
-#       %div
-#         = message.content
-#         %br/
-#         - if current_user == message.user
-#           = link_to "削除", user_message_path(current_user, message), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs'
-#     %hr/
-# %h2 メッセージ
-# = form_for message, url:{action: :create} do |f|
-#   = f.text_field :content
-#   %br/
-#   = f.submit '送信'
-# = link_to "ホームへ戻る", user_path(current_user)