config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :tasks do
    resources :searches, only: :index
  end
  resources :tasks do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get "following"
      get "followers"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  enum state: { "New": 0,
                "Doing": 1,
                "Completed!": 2,
                "Failure": 3 }

  def self.search(search)
    if search
      Task.where('task LIKE(?)', "%#{search}%")
    else
      Task.all
    end
  end
end

app/controllers/tasks/searches_controller.rb
class Tasks::SearchesController < ApplicationController
  def index
    @tasks = Task.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(10)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @tasks = Task.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end
  
  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save
      flash[:new_task] = "タスクをシェアしました。達成に向けて頑張りましょう！"
      redirect_to '/'
    else
      flash.now[:danger] = "送信に失敗しました。もう一度試してみてください。"
      render 'tasks/new'
    end
  end

  def edit
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    if task.save
      flash[:update_task] = "タスクを更新しました。"
      redirect_to "/tasks/#{task.id}"
    else
      flash.now[:danger] = "送信に失敗しました。もう一度試してみてください。"
      render 'tasks/new'
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    flash[:delete_task] = "タスクを削除しました。"
    redirect_to '/'
  end

  def show
    @comment = Comment.new
    @comments = @task.comments.includes(:user)
    @like = Like.new
  end

  private
  def task_params
    params.require(:task).permit(:state, :task, :limit_date).merge(user_id: current_user.id)
  end

  def set_task
    @task = Task.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/tasks/searches_helper.rb
module Tasks::SearchesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_post_task.html.haml
.contents.row
  .container
    .container-inner
      = form_with(model: @task, local: true) do |f|
        .posting-task
          タスクをシェア
        .posting-task__task-content
          = f.text_area :task, placeholder: "taskを入力してください" , required: ""
        .posting-task__info-bar
          .state
            ステータス
          .limit
            リミット
        .posting-task__input-task
          .input-state
            = f.select :state, Task.states.keys, { required: "" }
          .input-limit
            = f.date_field :limit_date, required: ""
        .posting-task__submit
          = f.submit "シェア" 

app/views/tasks/_task.html.haml
.tasks-table
  .task-user
    %ul
      %li
        - if t.user.image?
          = link_to "/users/#{t.user.id}", class: "image-a" do
            = image_tag t.user.image.url, class: "user-icon", id: "img_prev"
        - else
          = link_to "/users/#{t.user.id}", class: "icon-a" do
            %i.far.fa-user-circle
      %li
        %a.user-mame{href: "/users/#{t.user.id}"}
          %span.user-name= t.user.nickname
      - if user_signed_in? && current_user.id == t.user.id
        %li.details
          = link_to '…', edit_task_path(t)
      - else
        %li.details
          .details-none
            …
  .tasks-box
    .limit-box
      .limit-upper
        .limit リミット
      .limit-lower
        .limit-date= t.limit_date
    .task-box
      .task-upper
        .task タスク
        .task-data
          = link_to task_path(t), method: :get do
            .task-data-inner= simple_format(t.task)
          .notification
            .notification__likes
              - if t.likes.size == 0
              - else
                - if user_signed_in?
                  - if current_user.already_liked?(t)
                    = link_to task_like_path(id: t.id, task_id: t.id), method: :delete do
                      %i.far.fa-thumbs-up
                      %p.count= t.likes.size
                  - else
                    = link_to task_likes_path(id: t.id, task_id: t.id), method: :post do
                      %i.far.fa-thumbs-up
                      %p.count= t.likes.size
                - else
                  = link_to new_user_session_path do
                    %i.far.fa-thumbs-up
                    %p.count= t.likes.size
            .notification__comments
              - if t.comments.size == 0
              - else
                = link_to "/tasks/#{t.id}" do
                  %i.far.fa-comment-dots
                  - if t.comments.size <= 99
                    %p.count= t.comments.size
                  - else
                    %p.count +99
          .created-date= t.created_at.to_s(:datetime)
          - if user_signed_in? && current_user.id == t.user.id
            .status-table
              = link_to edit_task_path(t) do
                .now-state= t.state
          - else
            .status-table
              = link_to task_path(t), method: :get do
                .others-now-state= t.state
  .other-box
    %ul
      - if user_signed_in?
        - if current_user.already_liked?(t)
          %li
            .check-good
              いいねをしています
            .like-orange
              = link_to task_like_path(id: t.id, task_id: t.id), id: "like_btn", method: :delete do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_like_path(id: t.id, task_id: t.id), method: :delete, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
        - else
          %li
            .like-none
              = link_to task_likes_path(id: t.id, task_id: t.id), method: :post do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_likes_path(id: t.id, task_id: t.id), method: :post, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
      - else
        %li
          .like-none
            = link_to new_user_session_path do
              %i.far.fa-thumbs-up
      %li
        - if t.comments.size == 0
          = link_to task_path(t), method: :get do
            %i.far.fa-comment-dots
        - else
          = link_to task_path(t), method: :get do
            %i.far.fa-comment-dots.a-comments
            - if user_signed_in? && current_user.id == t.user.id
              .notification-circle
                - if t.comments.size <= 9
                  .notification-circle__count
                    = t.comments.size
                - else
                  .notification-circle__dots
                    ・
            - else
    .adjustment-box

app/views/tasks/_welcome.html.haml
- if user_signed_in?
  .first-access-hidden(style="display: none;")
- else
  .first-wapper
    .first-access-wapper
      .wapper-left
        = image_tag asset_path("/images/Calendar_PNG.png"), style: "height: 120px; width: 90px;", class: "calender"
        = image_tag asset_path("/images/Books_PNG.png"), style: "height: 90px; width: 80px;", class: "books"
        = image_tag asset_path("/images/Degital_marketing_PNG.png"), style: "height: 120px; width: 120px;", class: "marketing"
      .wapper-center
        .first-access
          .first-access__upper
            .greeting
              .greeting__top
                ようこそ！
              .greeting__mid
                our taskへ
          .first-access__mid
            .introduction
              .introduction__top
                our taskではあなたのタスクをシェアできます
              .introduction__mid
                あなたのタスクを他のユーザーに共有して
              .introduction__low
                リミットまでに達成しましょう！
          .first-access__low
            = link_to  "our task をはじめる", new_user_registration_path, class: "first-access-btn"
      .wapper-right
        = image_tag asset_path("/images/fitness_PNG.png"), style: "height: 100px; width: 100px;", class: "fitness"
        = image_tag asset_path("/images/app_development_PNG.png"), style: "height: 150px; width: 150px;", class: "computer"

app/views/tasks/edit.html.haml
.contents.row
  .container
    .container-inner
      = form_with(model: @task, local: true) do |f|
        .posting-task
          タスクの編集
        .posting-task__task-content
          = f.text_area :task, placeholder: "taskを入力してください" , required: ""
        .posting-task__info-bar
          .state
            ステータス
          .limit
            リミット
        .posting-task__input-task
          .input-state
            = f.select :state, Task.states.keys, { required: "" }
          .input-limit
            = f.date_field :limit_date, required: ""
        .posting-task__submit
          = f.submit "編集"
          = link_to "削除", task_path(@task.id), method: :delete, data: { confirm: '本当に削除しますか？' }

app/views/tasks/index.html.haml
= render partial: "welcome"
.tasks
  .main-table
    %ul
      - if user_signed_in?
        %li
          = link_to "タスクをシェア", "/tasks/new", class: "post-task"
        %li
          = link_to "マイページ", "/users/#{current_user.id}", class: "my-page"
      - else
        %li
          = link_to "ログイン", new_user_session_path, class: "post-task"
        %li
          = link_to "登録する", new_user_registration_path, class: "my-page"
  = form_with(url: tasks_searches_path, local: true, method: :get, class: "search-form") do |f|
    .search-inner
      = f.text_field :keyword, placeholder: "タスクを検索", class: "search-input"
      = f.button type: "submit", style: 'border-style: none;', class: "search-btn" do
        %i.fas.fa-search
  .sort-box
  - @tasks.each do |t|
    = render partial: "task", locals: { t: t }
  = paginate(@tasks)
-# .side-ber
-#   開発段階

app/views/tasks/new.html.haml
= render partial: "tasks/post_task"

app/views/tasks/show.html.haml
.task-comment
  #comment-area.tasks
    .tasks-table
      .task-user
        %ul
          %li
            - if @task.user.image?
              = link_to "/users/#{@task.user.id}", class: "image-a" do
                = image_tag @task.user.image.url, class: "user-icon", id: "img_prev"
            - else
              = link_to "/users/#{@task.user.id}", class: "icon-a" do
                %i.far.fa-user-circle
          %li
            %a.user-name{href: "/users/#{@task.user.id}"}
              %span.user-name= @task.user.nickname
          - if user_signed_in? && current_user.id == @task.user.id
            %li.details
              = link_to "…", "/tasks/#{@task.id}/edit"
          - else
            %li.details
              .details-none
                …
      .tasks-box
        .limit-box
          .limit-upper
            .limit LIMIT
          .limit-lower
            .limit-date= @task.limit_date
        .task-box
          .task-upper
            .task TASK
            .task-data
              .task-data-inner= simple_format(@task.task)
              .created-date= @task.created_at.to_s(:datetime)
              - if user_signed_in? && current_user.id == @task.user.id
                .status-table
                  %a(href="/tasks/#{@task.id}/edit")
                    .now-state= @task.state
              - else
                .status-table
                  .others-now-state= @task.state
    .counts-table
      .like-counts
        - if user_signed_in?
          - if current_user.already_liked?(@task)
            .like-circle-orange
              = link_to task_like_path(@task), id: "like_btn", method: :delete do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_like_path(@task), method: :delete, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
          - else
            .like-circle-none
              = link_to task_likes_path(@task), id: "like_btn", method: :post do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_likes_path(@task), method: :post, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
        - else
          .like-circle-none
            = link_to new_user_session_path do
              %i.far.fa-thumbs-up

        .counts
          = @task.likes.size
      .comment-counts
        - if @task.comments.size == 0
          %a.comment-circle-zero(href="#comment-area")
            %i.far.fa-comment-dots
        - else
          %a.comment-circle(href="#comment-area")
            %i.far.fa-comment-dots
        .counts
          = @task.comments.size

    .container.comments-container
      - if current_user
        = form_with(model: [@task, @comment], local: true) do |f|
          = f.text_field :text, placeholder: "コメントを入力", rows: "2", class: "container__text-area", required: ""
          = f.button type: "submit", class: "container__submit" do
            %i.far.fa-paper-plane
      - else
        .ask-for-login
          %p.ask-for-login__upper コメントをするにはログインもしくはアカウント登録が必要です
          .ask-for-login__lower
            %i.fas.fa-sign-in-alt
        .login-form
          = link_to "Sign up", new_user_registration_path, class: "signin_from_show"
          = link_to "Log in", new_user_session_path, class: "login_from_show"

      .comments
        - @comments.each do |c|
          .comments__comment
            -# - if c.user_id == c.task_id
            - if @task.user_id == c.user.id
              .owner
                .owner__owner-comment
                  .a-comment
                    = c.text
                  .remove-comment
                    - if user_signed_in? && c.user.id == current_user.id
                      = link_to task_comment_path(task_id: @task, id: c.id), method: :delete, data: { confirm: '本当に削除しますか？' } do
                        削除
                .owner__owner-info
                  = link_to c.user.nickname, "/users/#{c.user_id}", class: "user-name"
                  - if c.user.image?
                    = link_to "/users/#{c.user.id}", class: "image-a" do
                      = image_tag c.user.image.url, class: "user-icon", id: "img_prev"
                  - else
                    = link_to "/users/#{c.user.id}", class: "icon-a" do
                      %i.far.fa-user-circle
                  .post-date= c.created_at.to_s(:datetime)
            - else
              .other-user
                .other-user__users-info
                  - if c.user.image?
                    = link_to "/users/#{c.user.id}", class: "image-a" do
                      = image_tag c.user.image.url, class: "user-icon", id: "img_prev"
                  - else
                    = link_to "/users/#{c.user.id}", class: "icon-a" do
                      %i.far.fa-user-circle
                  = link_to c.user.nickname, "/users/#{c.user_id}", class: "user-name"
                  .post-date= c.created_at.to_s(:datetime)
                .other-user__users-comment
                  .a-comment
                    = c.text
                  .remove-comment
                    - if user_signed_in? && c.user.id == current_user.id
                      = link_to task_comment_path(task_id: @task, id: c.id), method: :delete, data: { confirm: '本当に削除しますか？' } do
                        削除
    .top-page
      = link_to "トップページ", "/", class: "return-top"