config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :tasks do
    resources :searches, only: :index
  end
  resources :tasks do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get "following"
      get "followers"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like, dependent: :destroy
  has_many :liked_tasks, through: :likes, source: :task
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :messages
  has_many :sent_messages, through: :messages, source: :receive_user
  has_many :reverses_of_message, class_name: 'Message', foreign_key: 'receive_user_id'
  has_many :received_messages, through: :reverses_of_message, source: :user

  mount_uploader :image, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def already_liked?(task)
    self.like.exists?(task_id: task.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def followers?(other_user)
    self.followers.include?(other_user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :following, :followers]
  before_action :check_guest, only: [:update, :destroy]

  def index
    @users = User.all
  end

  def new
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end
  
  def update
    if current_user.update(user_params) && @user.save
      flash[:new_task] = "プロフィールを更新しました。"
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = "プロフィールの更新に失敗しました。"
      redirect_to edit_user_path(current_user)
    end
  end
  
  def show
    @image = @user.image
    @tasks = @user.tasks.order("created_at DESC").page(params[:page]).per(10)
    @likes = Like.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(10)
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room.id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  
  def destroy
  end

  def following
  end

  def followers
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to user_path(current_user), method: :get
      flash[:guest_alert] = 'ゲストユーザーの変更・削除はできません。'
    end
  end

  def user_params
    params.fetch(:user, {}).permit(:nickname)
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname, :profile, :site, :twitter, :facebook, :instagram, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_like_tasks.html.haml
.tasks-table
  .task-user
    %ul
      %li
        - if like.task.user.image?
          = link_to "/users/#{like.task.user.id}", class: "image-a" do
            = image_tag like.task.user.image.url, class: "user-icon", id: "img_prev"
        - else
          = link_to "/users/#{like.task.user.id}", class: "icon-a" do
            %i.far.fa-user-circle
      %li
        %a.user-mame{href: "/users/#{like.task.user.id}"}
          %span.user-name= like.task.user.nickname
      - if user_signed_in? && current_user.id == like.task.user.id
        %li.details
          = link_to '…', "/tasks/#{like.task.id}/edit"
      - else
        %li.details
          .details-none
            …
  .tasks-box
    .limit-box
      .limit-upper
        .limit リミット
      .limit-lower
        .limit-date= like.task.limit_date
    .task-box
      .task-upper
        .task タスク
        .task-data
          .task-data-inner= simple_format(like.task.task)
          .notification
            .notification__likes
              - if like.task.likes.size == 0
              - else
                - if user_signed_in?
                  - if current_user.already_liked?(like.task)
                    = link_to task_like_path(id: like.task.id, task_id: like.task.id), method: :delete do
                      %i.far.fa-thumbs-up
                      %p.count= like.task.likes.size
                  - else
                    = link_to task_likes_path(id: like.task.id, task_id: like.task.id), method: :post do
                      %i.far.fa-thumbs-up
                      %p.count= like.task.likes.size
                - else
                  = link_to new_user_session_path do
                    %i.far.fa-thumbs-up
                    %p.count= like.task.likes.size
            .notification__comments
              - if like.task.comments.size == 0
              - else
                = link_to "/tasks/#{like.task.id}" do
                  %i.far.fa-comment-dots
                  - if like.task.comments.size <= 99
                    %p.count= like.task.comments.size
                  - else
                    %p.count +99
          .created-date= like.task.created_at.to_s(:datetime)
          - if user_signed_in? && current_user.id == like.task.user.id
            .status-table
              %a(href="/tasks/#{like.task.id}/edit")
                .now-state= like.task.state
          - else
            .status-table
              .others-now-state= like.task.state
  .other-box
    %ul
      - if user_signed_in?
        - if current_user.already_liked?(like.task)
          %li
            .like-orange
              = link_to task_like_path(id: like.task.id, task_id: like.task.id), id: "like_btn", method: :delete do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_like_path(id: t.id, task_id: t.id), method: :delete, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
        - else
          %li
            .like-none
              = link_to task_likes_path(id: like.task.id, task_id: like.task.id), method: :post do
                -# -----↓非同期処理の記述↓-----
                -# = link_to task_likes_path(id: t.id, task_id: t.id), method: :post, remote: true do
                -# -----↑非同期処理の記述↑-----
                %i.far.fa-thumbs-up
      - else
        %li
          .like-none
            = link_to new_user_session_path do
              %i.far.fa-thumbs-up
      %li
        - if like.task.comments.size == 0
          %a(href="/tasks/#{like.task.id}")
            %i.far.fa-comment-dots
        - else
          %a(href="/tasks/#{like.task.id}")
            %i.far.fa-comment-dots.a-comments
            - if user_signed_in? && current_user.id == like.task.user.id
              .notification-circle
                - if like.task.comments.size <= 9
                  .notification-circle__count
                    = like.task.comments.size
                - else
                  .notification-circle__dots
                    ・
            - else
    .adjustment-box

app/views/users/_users_follow.html.haml
.follow-list__inner
  .users-info
    .users-image
      - if f.image?
        = link_to user_path(f.id), method: :get do
          = image_tag f.image.url, class: "image-a"
      - else
        = link_to user_path(f.id), method: :get do
          %i.far.fa-user-circle
    .users-name
      = link_to user_path(f.id), method: :get do
        = f.nickname
    .users-twitter
      - if f.twitter?
        = link_to f.twitter do
          %i.fab.fa-twitter
      - else
        %i.fab.fa-twitter.none
    .users-facebook
      - if f.facebook?
        = link_to f.facebook do
          %i.fab.fa-facebook
      - else
        %i.fab.fa-facebook.none
    .users-instagram
      - if f.instagram?
        = link_to f.instagram do
          %i.fab.fa-instagram
      - else
        %i.fab.fa-instagram.none
    .users-site
      - if f.site?
        = link_to f.site do
          %i.fas.fa-home
      - else
        %i.fas.fa-home.none
    .follow-select
      - if user_signed_in?
        - if user_signed_in? && f == current_user
        - else
          - if current_user.following?(f)
            = form_for(current_user.relationships.find_by(follow_id: f.id), html: { method: :delete }) do |t|
              = t.hidden_field :follow_id, value: f.id
              = t.button type: "submit", class: 'follow-select__unfollow-btn' do
                フォロー中
          - else
            = form_for(current_user.relationships.build) do |t|
              = t.hidden_field :follow_id, value: f.id
              = t.button type: "submit", class: 'follow-select__follow-btn' do
                フォロー
          -# -----メモ-----
          -#   = link_to "フォロー中", relationship_path(@user.id), method: :delete, class: "follow-select__unfollow-btn"
          -# - else
          -#   = link_to "フォロー", relationships_path(@user.id), method: :post, class: "follow-select__follow-btn"
          -# -----メモ-----
      - else
        = link_to "フォロー", new_user_session_path, class: "follow-select__follow-btn"
  .users-info-lower
    - if user_signed_in?
      - unless current_user == f
        - if current_user.followers?(f)
          .user-follower
            %i.far.fa-check-circle
            %p フォローされています

      -# .user-follower
      -#   %i.far.fa-check-circle
      -#   %p フォローされています

app/views/users/_users_info_upper.html.haml
.users__top
  .user-info
    .user-info__left
      .profile-image
        - if @user.image?
          = image_tag @user.image.url
        - else
          %i.far.fa-user-circle
    .user-info__center
    .user-info__right
      .info-right
        .info-right__name
          .name
            = link_to user_path(@user.id), method: :get do
              = @user.nickname
          .edit
            - if user_signed_in? && @user == current_user
              = link_to edit_user_path(current_user) do
                %i.fas.fa-user-cog
                %p
                  プロフィール編集
            - else
              - if user_signed_in?
                - unless current_user == @user
                  - if current_user.following?(@user)
                    = form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f|
                      = f.hidden_field :follow_id, value: @user.id
                      = f.button type: "submit", class: 'follow-now' do
                        %p
                          フォロー中
                        %i.fas.fa-user-check
                  - else
                    = form_for(current_user.relationships.build) do |f|
                      = f.hidden_field :follow_id, value: @user.id
                      = f.button type: "submit", class: 'following' do
                        %p
                          フォロー
                        %i.fas.fa-user-plus
              - else
                %button{class: 'following'}
                  = link_to user_session_path do
                    %p
                      フォロー
                    %i.fas.fa-user-plus
        .info-right__follow-info
          - if user_signed_in?
            - unless current_user == @user
              - if current_user.followers?(@user)
                .user-follower
                  %i.far.fa-check-circle
                  %p フォローされています
              - else
          - else
        .info-right__sns
          .twitter
            - if @user.twitter?
              = link_to @user.twitter do
                %i.fab.fa-twitter
            - else
              %i.fab.fa-twitter.none
          .facebook
            - if @user.facebook?
              = link_to @user.facebook do
                %i.fab.fa-facebook
            - else
              %i.fab.fa-facebook.none
          .instagram
            - if @user.instagram?
              = link_to @user.instagram do
                %i.fab.fa-instagram
            - else
              %i.fab.fa-instagram.none
          .mysite-logo
            - if @user.site?
              %i.fas.fa-home
            - else
              %i.fas.fa-home.none
          .mysite
            - if @user.site?
              = link_to @user.site do
                = @user.site
            - else
              .nil_date
                web site
        .info-right__follow
          .task-count
            - if current_page?(user_path)
              = link_to "#task-list", class: "move_tasks-list" do
                タスク
                %b= @user.tasks.count
                件
            - else
              = link_to user_path(@user.id), method: :get, class: "move_tasks-list" do
                タスク
                %b= @user.tasks.count
                件
          .following
            = link_to following_user_path(@user) do
              フォロー中
              %b= @user.followings.count
              人
          .follower
            = link_to followers_user_path(@user) do
              フォロワー
              %b= @user.followers.count
              人
        .info-right__profile
          .introduce
            - if @user.profile?
              = simple_format(@user.profile)
            - else
              .nil_date
                profile

app/views/users/edit.html.haml
.contents.row
  .container
    .container-inner
      = form_with model: @user, local: true do |f|
        .inner-info
          .inner-info__nav
            .user-edit_tabs.tab
              %a.basic-info-tab.active(href="#tab3")
                基本情報
              %a.sns-account-tab(href="#tab4")
                SNS・ウェブサイト
          #tab3.inner-info__main.tabContents.active
            .user-image
              .user-image__left
                - if @user.image?
                  = image_tag @user.image.url, style: "height: 150px; width: 150px; border-radius: 50%;", id: "img_prev"
                - else
                  %i.far.fa-user-circle
              .user-image__right
                %label
                  .dipslay-hidden
                    = f.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "user_img"
                  .select-image
                    プロフィール写真を変更
            .user-nickname
              .user-nickname__left
                ニックネーム
              .user-nickname__right
                = f.text_field :nickname, maxlength: "8"
            .user-email
              .user-email__left
                メールアドレス
              .user-email__right
                = f.email_field :email
            .user-profile
              .user-profile__left
                プロフィール
              .user-profile__right
                = f.text_area :profile
          #tab4.inner-info__sub.tabContents
            .twitter-account
              .twitter-account__left
                Twitter
              .twitter-account__right
                = f.text_field :twitter, placeholder: "https://twitter.com/(アカウント名)"
            .facebook-account
              .facebook-account__left
                Facebook
              .facebook-account__right
                = f.text_field :facebook, placeholder: "https://www.facebook.com/profile.php?(IDが入ります)"
            .instagram-account
              .instagram-account__left
                Instagram
              .instagram-account__right
                = f.text_field :instagram, placeholder: "https://www.instagram.com/(アカウント名)"
            .user-site
              .user-site__left
                ウェブサイト
              .user-site__right
                = f.text_field :site
            .introduce
              .introduce__sns
                ・各SNSのリンクはマイページのリンクを貼り付けてください
              .introduce__mysite
                ・ウェブサイトにはあなたのウェブサイトやブログサイトなど自由に貼り付けることが出来ます
          .inner-info__aside
        .user-submit
          = f.submit "更新", class: "user-submit__btn"
          = link_to "もどる", user_path(current_user), class: "return-mypage"

app/views/users/followers.html.haml
.users
  = render partial: "users_info_upper"
  .users__low
    .select-tabs
      .inner-tabs.tab
        %a.task-tab.active(href="#tab5")
          フォロワー
          (
          = @user.followers.count
          人)
        %a.like-tab(href="#tab6")
          フォロー中
          (
          = @user.followings.count
          人)
  #tab5.follow-list.tabContents.active
    - if @user.followers.count == 0
      .followers-user-none
        %p
          まだフォロワーはいません
          %i.fas.fa-users
    - else
      - @user.followers.each do |f|
        = render partial: "users_follow", locals: { f: f }
  #tab6.follow-list.tabContents
    - if @user.followings.count == 0
      .followings-user-none
        %p
          まだフォローしているユーザーはいません
          %i.fas.fa-users
    - else
      - @user.followings.each do |f|
        = render partial: "users_follow", locals: { f: f }

app/views/users/following.html.haml
.users
  = render partial: "users_info_upper"
  .users__low
    .select-tabs
      .inner-tabs.tab
        %a.task-tab.active(href="#tab6")
          フォロー中
          (
          = @user.followings.count
          人)
        %a.like-tab(href="#tab5")
          フォロワー
          (
          = @user.followers.count
          人)
  #tab6.follow-list.tabContents.active
    - if @user.followings.count == 0
      .followings-user-none
        %p
          まだフォローしているユーザーはいません
          %i.fas.fa-users
    - else
      - @user.followings.each do |f|
        = render partial: "users_follow", locals: { f: f }
  #tab5.follow-list.tabContents
    - if @user.followers.count == 0
      .followers-user-none
        %p
          まだフォロワーはいません
          %i.fas.fa-users
    -else
      - @user.followers.each do |f|
        = render partial: "users_follow", locals: { f: f }

app/views/users/show.html.haml
.users
  = render partial: "users_info_upper"
  #task-list.users__low
    .select-tabs
      .inner-tabs.tab
        %a.task-tab.active(href="#tab1")
          = @user.nickname
          さんのタスク
          (
          = @user.tasks.size
          件)
        %a.like-tab(href="#tab2")
          いいねしたタスク
          (
          = @user.like.size
          件)
    #tab1.tasks.user-tasks.tabContents.active
      - if @user.tasks.size == 0
        .task-zero
          %p
            タスクがありません
          %i.fas.fa-tasks
        - if user_signed_in? && @user == current_user
          .post-task
            = link_to "タスクをシェアする", new_task_path, class: "post-task__btn"
      - else
        - @tasks.each do |t|
          = render partial: "tasks/task", locals: { t: t }
        = paginate(@tasks)
    #tab2.tasks.like-tasks.tabContents
      - if @user.like.size == 0
        .like-zero
          %p
            いいねしたタスクはありません
          %i.fas.fa-tasks
        .watching-tasks
          = link_to "タスクを見に行く", root_path, class: "watching-tasks__btn"
      - else
        - @likes.each do |like|
          = render partial: "users/like_tasks", locals: { like: like }
        = paginate(@likes)
    .top-page
      = link_to "トップページ", "/", class: "return-top"


= link_to "メッセージ", message_path(@user), method: :get
= link_to "メッセージ", messages_path, method: :get