config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :tasks do
    resources :searches, only: :index
  end
  resources :tasks do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get "following"
      get "followers"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages
end

app/views/layouts/_flash.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_footer.html.haml
- if user_signed_in?
  #appear-share-task.appear-share-task
    = link_to new_task_path, class: "appear-share-task__btn" do
      %i.fas.fa-share-alt
  #appear-info.appear-info
    .appear-info__text
      タスクをシェア
- else
  #appear.administrator-login
    = link_to users_guest_sign_in_path, method: :post, data: { confirm: 'ゲストユーザーとしてログインしますか？' }, class: "administrator-login__btn" do
      %p
        簡単ログイン
      %i.fas.fa-key
#page-top.icon-box
  %p#slide-text
    TOP
  %i.fas.fa-chevron-up
%footer
  Copyright
  %span.copyright © 
  2020 our task All Rights Reserved.

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_title_ber.html.haml
.title-bar
  .title-box
    .title-box-inner
      .title-name
        = link_to root_path do
          .our-task our task
        .our-task-icon
          %input(id="hamburger" type="checkbox")
          %label.fas.fa-share-alt(for="hamburger" class="hamburger-open")
          %label(for="hamburger" class="hamburger-back")
          %aside
            %label(for="hamburger" class="hamburger-close")
              %i.fas.fa-bars
            %nav
              .menu-list
                - if user_signed_in?
                  -if current_page?(root_path)
                  - else
                    = link_to "トップページ", root_path, class: "menu-list__toppage"
                  = link_to "マイページ", user_path(current_user.id), method: :get, class: "menu-list__mypage"
                  = link_to "シェアタスク", new_task_path, class: "menu-list__share-task"
                  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu-list__logout"
                  .media-screen-footer
                    .media-screen-footer__top
                      Copyright
                      %span.copyright © 
                      2020 our task
                    .media-screen-footer__low
                      All Rights Reserved.
                - else
                  -if current_page?(root_path)
                  - else
                    = link_to "トップページ", root_path, class: "menu-list__toppage"
                  = link_to "ログイン", new_user_session_path, class: "menu-list__login"
                  = link_to "登録する", new_user_registration_path, class: "menu-list__signin"
                  .menu-list__logout
                  .media-screen-footer
                    .media-screen-footer__top
                      Copyright
                      %span.copyright © 
                      2020 our task
                    .media-screen-footer__low
                      All Rights Reserved.
      - if user_signed_in?
        %ul.user-sign-in
          %li
            %a#current_user.new(href="/users/#{current_user.id}")
              %span#current_user.new= current_user.nickname
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'log-out'
      - else
        %ul.user-sign-in
          %li
            = link_to "登録する", new_user_registration_path, class: 'new', id: 'up'
          %li
            = link_to "ログイン", new_user_session_path, class: 'log-in'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title OurTask
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-170074285-2"}
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-170074285-2');
    %link{href: "https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c", rel: "stylesheet"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}
    %script{src: "https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"}
  %body
    .overlay
      .btn_area
        .btn_area__top
          %h1
            ようこそ！
          %p
            our taskではあなたのタスクをシェアできます。
            %br/
            %br/
            登録をしてみんなにタスクをシェアしてみましょう！
        .btn_area__mid
          = image_tag asset_path("/images/share_task.png"), style: "height: 220px; width: 260px;", class: "share_task"
          
        .btn_area__low
          -# = link_to "our taskを始める", new_user_registration_path, class: "first-task"
          %button 閉じる
    = render "layouts/title_ber"
    = render "layouts/notification"
    = yield
= render "layouts/footer"